spring:
  application:
    name: MSFive
  --cloud:
    --config:
      --uri: http://localhost:9090
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1112/eureka}
##spring.data.mongodb.database: my-db-engine
spring.data.mongodb.uri: mongodb://127.0.0.1:27017/test


#
logging:
  file: /var/log/logs/MSFive.log