spring:
  application:
    name: MSFive
  --cloud:
    --config:
      --uri: http://localhost:9090
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1112/eureka}
      
