spring:
  application:
    name: MSThree
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1112/eureka}
      
logging:
  file: /var/log/logs/MSThree.log